version: '2'
services:
    converter-app:
        image: converter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://converter-mysql:3306/converter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=converter-elasticsearch:9300
        ports:
            - 8080:8080
    converter-mysql:
        extends:
            file: mysql.yml
            service: converter-mysql
    converter-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: converter-elasticsearch
